name: spotife
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.3.0
  dio: ^5.0.0
  flutter_secure_storage: ^9.0.0
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib\icon\Spotify_icon.svg.png

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#191414"         # Nền tối giống Spotify
  image: lib/icon/spotify.png  # Logo ở giữa
  fullscreen: true

  color_dark: "#000000"    # Nền cho dark mode
  image_dark: lib/icon/spotify.png

  android_12:
    color: "#191414"
    image: lib/icon/spotify.png
    icon_background_color: "#191414"
    color_dark: "#000000"
    image_dark: lib/icon/spotify.png
    icon_background_color_dark: "#000000"
